### PR TITLE
docs(readme): document unsupported TS compiler options

### PR DESCRIPTION
**Pull request by joelmukuthu**
### Before submitting the PR, please make sure you do the following

- [x] ~~It's really useful if your PR relates to an outstanding issue, so please reference it in your PR, or create an explanatory one for discussion. In many cases features are absent for a reason.~~ From [this comment](https://github.com/kaisermann/svelte-preprocess/issues/98#issuecomment-572854189) on issue #98 
- [x] ~~This message body should clearly illustrate what problems it solves. If there are related issues, remember to reference them.~~ N/A
- [x] ~~Ideally, include a test that fails without this PR but passes with it. PRs will only be merged once they pass CI. (Remember to `npm run lint`!)~~ N/A

### Tests

- [x] ~~Run the tests tests with `npm test` or `yarn test`~~ not necessary, I think.

### CODE REVIEW

**Comment by kaisermann** [comment]
Just came to my mind that we can, apart from documenting, override them in the typescript transformer: https://github.com/kaisermann/svelte-preprocess/blob/master/src/transformers/typescript.ts#L198.

What do you think?

**Comment by joelmukuthu** [comment]
Hmm, I think that might cause some confusion. I think a better option is maybe to warn the user if they try to use unsupported options. I can work on that too but probably won't be till next weekend.

I'd also like to add a little more info to the README as to why they're not supported, but frankly I'm a bit confused myself. I have this setup:

- `noUnusedLocals: true` in tsconfig.json
- `typescript: { tsconfigFile: './tsconfig.json' }` in svelte-preprocess's options
- an unused local variable in a `script lang="typescript"` tag in a Svelte component

Building the project via webpack works while running tests on Jest (with ts-jest transforming TS to JS) fails with a `ParseError: Unexpected character ''` error thrown by the svelte compiler. Does svelte-preprocess already ignore/bypass the TS compilation errors?

**Comment by kaisermann** [comment]
`svelte-preprocess` ignores only some import related diagnostics. Can you provide a minimal repro project?

**Comment by joelmukuthu** [comment]
@kaisermann you're right. I have a setup where a lot was going on and I couldn't reproduce it in a smaller project. Thank you for your time!

**Pull request merged**
